// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZuQnanNZbjdZs0eZQJnEgITgFfbFZnQ',
    appId: '1:758451518573:web:0fb37d338d68e289075364',
    messagingSenderId: '758451518573',
    projectId: 'bizora-68ec1',
    authDomain: 'bizora-68ec1.firebaseapp.com',
    storageBucket: 'bizora-68ec1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwoZbEZhIRg7pc_I_ZFq2JBbM_mq-Li-s',
    appId: '1:758451518573:android:79c258c0981ad07d075364',
    messagingSenderId: '758451518573',
    projectId: 'bizora-68ec1',
    storageBucket: 'bizora-68ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkF1TQCbeDjzqRZKNN8lsrKzOOQm5dZl8',
    appId: '1:758451518573:ios:77395a4ff6349239075364',
    messagingSenderId: '758451518573',
    projectId: 'bizora-68ec1',
    storageBucket: 'bizora-68ec1.firebasestorage.app',
    androidClientId: '758451518573-a97fvc55obp6s68fkrcgrt88b6si17ac.apps.googleusercontent.com',
    iosClientId: '758451518573-kli9326cj2n2092o1d4i0b7s0talca6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkF1TQCbeDjzqRZKNN8lsrKzOOQm5dZl8',
    appId: '1:758451518573:ios:77395a4ff6349239075364',
    messagingSenderId: '758451518573',
    projectId: 'bizora-68ec1',
    storageBucket: 'bizora-68ec1.firebasestorage.app',
    androidClientId: '758451518573-a97fvc55obp6s68fkrcgrt88b6si17ac.apps.googleusercontent.com',
    iosClientId: '758451518573-kli9326cj2n2092o1d4i0b7s0talca6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrZuQnanNZbjdZs0eZQJnEgITgFfbFZnQ',
    appId: '1:758451518573:web:caa29c463a765cb7075364',
    messagingSenderId: '758451518573',
    projectId: 'bizora-68ec1',
    authDomain: 'bizora-68ec1.firebaseapp.com',
    storageBucket: 'bizora-68ec1.firebasestorage.app',
  );
}
